#!/bin/sh -eu

ME=$(basename $0)

if echo $ME | grep -q '++$'; then
  RANCC=ran++
else
  RANCC=rancc
fi

RANCC=$(dirname $0)/../bin/$RANCC

if ! test -x $RANCC; then
  echo >&2 "fake-$ME: $RANCC missing"
  exit 1
fi

# Remove ourselves from PATH (to avoid recursion)
PATH=$(echo "$PATH" | tr : '\n' | grep -v fake-gcc | tr '\n' :)

exec $RANCC "$@"
