#!/usr/bin/python

# Copyright 2017-2019 Yury Gribov
#
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# TODO:
# * support 32-bits
# * detect self-recursion
# * auto-add -save-temps (?)

import sys
import os

verbose = 0
out = sys.stderr

def note(msg):
  if verbose > 0:
    out.write('ranas: %s\n' % msg)

def warn(msg):
  out.write('ranas: warning: %s\n' % msg)

def main():
  mydir = os.path.dirname(os.path.abspath(__file__))

  global verbose
  verbose = int(os.getenv('RANCC_VERBOSE', '0'))
  cc = os.getenv('RANCC_CC', 'gcc')
  cxx = os.getenv('RANCC_CXX', 'g++')
  tooldir = os.getenv('RANCC_TOOL_DIR', os.path.join(mydir, '../libexec'))

  global out
  out_name = os.getenv('RANCC_OUTPUT', None)
  if out_name:
    out = open(out_name, 'a')

  argv_string = ' '.join(sys.argv)
  note('initial args: %s' % argv_string)

  args = [cxx if '++' in sys.argv[0] else cc]
  has_B = False

  for arg in sys.argv[1:]:
    if arg.startswith('-B'):
      has_B = True
    elif arg == '-pipe':
      # Stripping, many packages fail to instrument because of this
      # (e.g. perl, systemd, pulseaudio, insserv, rtkit, apache2, iptables, pulseaudio, vim)
      continue
    args.append(arg)

  if has_B:
    warn('not instrumenting: -B given: %s' % argv_string)
  else:
    args.append('-B' + tooldir)

  note('preprocessed args: %s' % ' '. join(args))

  out.flush()
  sys.stdout.flush()
  sys.stderr.flush()

  os.execvp(args[0], args)

if __name__ == '__main__':
  main()
