#!/usr/bin/env python3

# Copyright 2017-2022 Yury Gribov
#
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

"""
Compiler wrapper which sole purpose is to redirect asm calls to ranas.
"""

# TODO:
# * support 32-bits
# * detect self-recursion
# * auto-add -save-temps (?)

import sys
import os
import subprocess

verbose = 0
out = sys.stderr

def note(msg):
  if verbose > 0:
    out.write(f'ranas: {msg}\n')

def warn(msg):
  out.write(f'ranas: warning: {msg}\n')

def main():
  mydir = os.path.dirname(os.path.abspath(__file__))

  global verbose
  verbose = int(os.getenv('RANCC_VERBOSE', '0'))
  cc = os.getenv('RANCC_CC', 'gcc')
  cxx = os.getenv('RANCC_CXX', 'g++')
  tooldir = os.getenv('RANCC_TOOL_DIR', os.path.join(mydir, '../libexec'))

  global out
  out_name = os.getenv('RANCC_OUTPUT', None)
  if out_name:
    out = open(out_name, 'a')  # pylint: disable=consider-using-with

  argv_string = ' '.join(sys.argv)
  note(f'initial args: {argv_string}')

  args = [cxx if '++' in sys.argv[0] else cc]
  has_B = False

  for arg in sys.argv[1:]:
    if arg.startswith('-B'):
      has_B = True
    elif arg == '-pipe':
      # Stripping, many packages fail to instrument because of this
      # (e.g. perl, systemd, pulseaudio, insserv, rtkit, apache2, iptables, pulseaudio, vim)
      continue
    args.append(arg)

  if has_B:
    warn(f'not instrumenting: -B given: {argv_string}')
  else:
    args.append('-B' + tooldir)

  note('preprocessed args: ' + ' '. join(args))

  out.flush()
  sys.stdout.flush()
  sys.stderr.flush()

  if 'coverage' in sys.modules:
    with subprocess.Popen(args, stdin=None, stdout=subprocess.PIPE, stderr=subprocess.PIPE) as p:
      out, err = p.communicate()
    sys.stdout.buffer.write(out)
    sys.stderr.buffer.write(err)
    sys.exit(p.returncode)

  os.execvp(args[0], args)

if __name__ == '__main__':
  main()
